ALTER TABLE "applications" ALTER COLUMN "biochar_applied_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "applications" ALTER COLUMN "biochar_applied_dry_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "applications" ALTER COLUMN "co2e_stored_tonnes" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "weight_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "buffer_pool_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "h_to_c_org_ratio" SET DATA TYPE numeric(7, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "mean_random_reflectance_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "std_random_reflectance" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "mean_non_reactive_carbon_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "std_non_reactive_carbon_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "f_durable_calculated" SET DATA TYPE numeric(7, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "total_co2e_stored_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "total_co2e_emissions_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "total_co2e_counterfactual_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "total_feedstock_mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "ineligible_feedstock_mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "ch4_composition_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "ch4_ppm" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "co_composition_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "co_ppm" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "co2_composition_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "co2_ppm" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "n2o_composition_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "credit_batches" ALTER COLUMN "n2o_ppm" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "feedstock_deliveries" ALTER COLUMN "wet_mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "feedstock_deliveries" ALTER COLUMN "moisture_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "feedstocks" ALTER COLUMN "mass_wet_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "feedstocks" ALTER COLUMN "mass_dry_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "feedstocks" ALTER COLUMN "moisture_content_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "feedstocks" ALTER COLUMN "co2e_feedstock_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "feedstocks" ALTER COLUMN "counterfactual_emissions_15_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "feedstocks" ALTER COLUMN "counterfactual_storage_50_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "feedstocks" ALTER COLUMN "market_leakage_tons" SET DATA TYPE numeric(14, 6);--> statement-breakpoint
ALTER TABLE "production_run_feedstocks" ALTER COLUMN "mass_used_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "production_runs" ALTER COLUMN "biochar_output_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "production_runs" ALTER COLUMN "biochar_moisture_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "production_runs" ALTER COLUMN "biochar_dry_mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "production_runs" ALTER COLUMN "feedstock_wet_mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "production_runs" ALTER COLUMN "feedstock_moisture_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "production_runs" ALTER COLUMN "feedstock_mass_dry_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "h_to_c_org_ratio" SET DATA TYPE numeric(7, 6);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "o_to_c_org_ratio" SET DATA TYPE numeric(7, 6);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "arsenic_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "cadmium_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "chromium_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "copper_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "lead_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "mercury_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "nickel_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "zinc_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "pah_total_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "pcb_total_mg_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "dioxins_ng_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "samples" ALTER COLUMN "furans_ng_kg" SET DATA TYPE numeric(10, 4);--> statement-breakpoint
ALTER TABLE "biochar_products" ALTER COLUMN "mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "biochar_products" ALTER COLUMN "moisture_content_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "biochar_products" ALTER COLUMN "water_added_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "formulation_ingredients" ALTER COLUMN "ratio" SET DATA TYPE numeric(7, 6);--> statement-breakpoint
ALTER TABLE "formulations" ALTER COLUMN "biochar_ratio" SET DATA TYPE numeric(7, 6);--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "moisture_content_percent" SET DATA TYPE numeric(9, 6);--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "delivered_wet_mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "deliveries" ALTER COLUMN "mass_dry_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "transport_legs" ALTER COLUMN "load_mass_kg" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "biochar_storage_inventory" ALTER COLUMN "quantity_kg_stored" SET DATA TYPE numeric(14, 3);--> statement-breakpoint
ALTER TABLE "biochar_storage_inventory" ALTER COLUMN "quantity_kg_remaining" SET DATA TYPE numeric(14, 3);