/**
 * Seed Data — Logistics, Applications & Credits
 *
 * Orders, deliveries, applications, and credit batches for both
 * Moshi and Arusha facilities.
 */
import * as schema from './schema';
import { ids, demoTimestamps } from './seed-constants';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SeedTx = { insert: (table: any) => { values: (data: any) => Promise<any> } };

/** Seed orders, deliveries, applications, and credit batches inside an existing transaction. */
export async function seedLogistics(tx: SeedTx) {
  console.log('Creating orders...');
  await tx.insert(schema.orders).values([
    {
      id: ids.order1,
      code: 'OR-2026-101',
      facilityId: ids.facilityMoshi,
      orderDate: demoTimestamps.order1Date,
      customerId: ids.customerCoffee,
      customerLocationId: ids.locationCoffeeNorth,
      biocharProductId: ids.biocharProduct1,
      quantityKg: 2000,
      packaging: 'bagged',
      value: 1500000,
    },
    {
      id: ids.order2,
      code: 'OR-2026-102',
      facilityId: ids.facilityMoshi,
      orderDate: demoTimestamps.order2Date,
      customerId: ids.customerTea,
      customerLocationId: ids.locationTeaEast,
      biocharProductId: ids.biocharProduct2,
      quantityKg: 1500,
      packaging: 'bagged',
      value: 1200000,
    },
    {
      id: ids.order3,
      code: 'OR-2026-103',
      facilityId: ids.facilityMoshi,
      orderDate: demoTimestamps.order3Date,
      customerId: ids.customerCoffee,
      customerLocationId: ids.locationCoffeeSouth,
      biocharProductId: ids.biocharProduct3,
      quantityKg: 1800,
      packaging: 'bagged',
      value: 1350000,
    },
    {
      id: ids.order4,
      code: 'OR-2026-104',
      facilityId: ids.facilityArusha,
      orderDate: demoTimestamps.order4Date,
      customerId: ids.customerVegetable,
      biocharProductId: ids.biocharProduct4,
      quantityKg: 900,
      packaging: 'loose',
      value: 675000,
    },
    {
      id: ids.order5,
      code: 'OR-2026-105',
      facilityId: ids.facilityArusha,
      orderDate: demoTimestamps.order5Date,
      customerId: ids.customerCoffee,
      customerLocationId: ids.locationCoffeeNorth,
      biocharProductId: ids.biocharProduct4,
      quantityKg: 750,
      packaging: 'bagged',
      value: 562500,
    },
  ]);

  console.log('Creating deliveries...');
  await tx.insert(schema.deliveries).values([
    {
      id: ids.delivery1,
      code: 'DL-2026-101',
      facilityId: ids.facilityMoshi,
      deliveryDate: demoTimestamps.delivery1Date,
      status: 'delivered',
      orderId: ids.order1,
      customerLocationId: ids.locationCoffeeNorth,
      biocharProductId: ids.biocharProduct1,
      storageLocationId: ids.storageProdMoshi,
      moistureContentPercent: 5.5,
      deliveredWetMassKg: 2000,
      massDryKg: 1890,
      driverId: ids.driverJackson,
      vehicleId: ids.vehicleTruck1,
    },
    {
      id: ids.delivery2,
      code: 'DL-2026-102',
      facilityId: ids.facilityMoshi,
      deliveryDate: demoTimestamps.delivery2Date,
      status: 'delivered',
      orderId: ids.order2,
      customerLocationId: ids.locationTeaEast,
      biocharProductId: ids.biocharProduct2,
      storageLocationId: ids.storageProdMoshi,
      moistureContentPercent: 4.8,
      deliveredWetMassKg: 1500,
      massDryKg: 1428,
      driverId: ids.driverAmina,
      vehicleId: ids.vehicleTruck2,
    },
    {
      id: ids.delivery3,
      code: 'DL-2026-103',
      facilityId: ids.facilityMoshi,
      deliveryDate: demoTimestamps.delivery3Date,
      status: 'delivered',
      orderId: ids.order3,
      customerLocationId: ids.locationCoffeeSouth,
      biocharProductId: ids.biocharProduct3,
      storageLocationId: ids.storageProdMoshi,
      moistureContentPercent: 6.0,
      deliveredWetMassKg: 1800,
      massDryKg: 1692,
      driverId: ids.driverJackson,
      vehicleId: ids.vehicleTruck1,
    },
    {
      id: ids.delivery4,
      code: 'DL-2026-104',
      facilityId: ids.facilityArusha,
      deliveryDate: demoTimestamps.delivery4Date,
      status: 'delivered',
      orderId: ids.order4,
      biocharProductId: ids.biocharProduct4,
      storageLocationId: ids.storageProdArusha,
      moistureContentPercent: 5.2,
      deliveredWetMassKg: 900,
      massDryKg: 853,
      driverId: ids.driverAmina,
      vehicleId: ids.vehicleTruck2,
    },
    {
      id: ids.delivery5,
      code: 'DL-2026-105',
      facilityId: ids.facilityArusha,
      deliveryDate: demoTimestamps.delivery5Date,
      status: 'delivered',
      orderId: ids.order5,
      customerLocationId: ids.locationCoffeeNorth,
      biocharProductId: ids.biocharProduct4,
      storageLocationId: ids.storageProdArusha,
      moistureContentPercent: 4.5,
      deliveredWetMassKg: 750,
      massDryKg: 716,
      driverId: ids.driverJackson,
      vehicleId: ids.vehicleTruck1,
    },
  ]);

  console.log('Creating applications...');
  await tx.insert(schema.applications).values([
    {
      id: ids.application1,
      code: 'AP-2026-101',
      applicationDate: demoTimestamps.application1Date,
      status: 'applied',
      deliveryId: ids.delivery1,
      biocharAppliedTons: 1.89,
      biocharAppliedDryTons: 1.79,
      gpsLatitude: -3.245,
      gpsLongitude: 37.425,
      fieldSizeHa: 1.2,
      cropType: 'Coffee',
      applicationMethodType: 'mechanical',
      fieldIdentifier: 'KILEMA-N-12',
      co2eStoredTonnes: 3.2,
      soilTemperatureSource: 'baseline',
      soilTemperatureC: 24.5,
    },
    {
      id: ids.application2,
      code: 'AP-2026-102',
      applicationDate: demoTimestamps.application2Date,
      status: 'applied',
      deliveryId: ids.delivery2,
      biocharAppliedTons: 1.43,
      biocharAppliedDryTons: 1.36,
      gpsLatitude: -4.789,
      gpsLongitude: 38.312,
      fieldSizeHa: 0.8,
      cropType: 'Tea',
      applicationMethodType: 'mechanical',
      fieldIdentifier: 'USAMBARA-E-1',
      co2eStoredTonnes: 2.4,
      soilTemperatureSource: 'baseline',
      soilTemperatureC: 22.8,
    },
    {
      id: ids.application3,
      code: 'AP-2026-103',
      applicationDate: demoTimestamps.application3Date,
      status: 'applied',
      deliveryId: ids.delivery3,
      biocharAppliedTons: 1.69,
      biocharAppliedDryTons: 1.59,
      gpsLatitude: -3.289,
      gpsLongitude: 37.198,
      fieldSizeHa: 1.0,
      cropType: 'Coffee',
      applicationMethodType: 'manual',
      fieldIdentifier: 'MACHAME-S-8',
      co2eStoredTonnes: 2.8,
      soilTemperatureSource: 'baseline',
      soilTemperatureC: 25.2,
    },
    {
      id: ids.application4,
      code: 'AP-2026-104',
      applicationDate: demoTimestamps.application4Date,
      status: 'delivered',
      deliveryId: ids.delivery4,
      biocharAppliedTons: 0.85,
      biocharAppliedDryTons: 0.81,
      gpsLatitude: -3.372,
      gpsLongitude: 36.694,
      fieldSizeHa: 1.5,
      cropType: 'Vegetables',
      applicationMethodType: 'manual',
      fieldIdentifier: 'ARUSHA-FARM-V3',
      co2eStoredTonnes: 1.4,
      soilTemperatureSource: 'global_database',
      soilTemperatureC: 23.1,
    },
    {
      id: ids.application5,
      code: 'AP-2026-105',
      applicationDate: demoTimestamps.application5Date,
      status: 'applied',
      deliveryId: ids.delivery5,
      biocharAppliedTons: 0.71,
      biocharAppliedDryTons: 0.68,
      gpsLatitude: -3.395,
      gpsLongitude: 36.712,
      fieldSizeHa: 2.0,
      cropType: 'Maize',
      applicationMethodType: 'mechanical',
      fieldIdentifier: 'ARUSHA-FARM-M7',
      co2eStoredTonnes: 1.2,
      soilTemperatureSource: 'baseline',
      soilTemperatureC: 22.4,
    },
  ]);

  console.log('Creating credit batches...');
  await tx.insert(schema.creditBatches).values([
    {
      id: ids.creditBatch1,
      code: 'CB-2026-101',
      facilityId: ids.facilityMoshi,
      status: 'pending',
      startDate: '2026-01-13',
      endDate: '2026-01-31',
      certifier: 'isometric',
      registry: 'Isometric Registry',
      weightTons: 5.01,
      bufferPoolPercent: 10,
      durabilityOption: '200_year',
      hToCorgRatio: 0.27,
      fDurableCalculated: 0.85,
      totalCo2eStoredTons: 8.4,
      totalCo2eEmissionsTons: 0.42,
      totalCo2eCounterfactualTons: 0.15,
    },
    {
      id: ids.creditBatch2,
      code: 'CB-2026-102',
      facilityId: ids.facilityMoshi,
      status: 'draft',
      startDate: '2026-02-01',
      endDate: '2026-02-28',
      certifier: 'isometric',
      registry: 'Isometric Registry',
      durabilityOption: '1000_year',
      meanRandomReflectancePercent: 2.8,
      meanNonReactiveCarbonPercent: 68,
    },
  ]);

  console.log('Creating credit batch application links...');
  await tx.insert(schema.creditBatchApplications).values([
    {
      id: ids.creditApp1,
      creditBatchId: ids.creditBatch1,
      applicationId: ids.application1,
    },
    {
      id: ids.creditApp2,
      creditBatchId: ids.creditBatch1,
      applicationId: ids.application2,
    },
    {
      id: ids.creditApp3,
      creditBatchId: ids.creditBatch1,
      applicationId: ids.application3,
    },
  ]);
}
