import type { DbTransaction } from '.';
import * as schema from './schema';
import { DEC_ORG_ID } from './org-defaults';
import { ids, demoTimestamps, demoProductionRunFeedstockWetMassKg, withBootstrapOrg } from './seed-demo-facts';
import { buildProductionRunReadings } from './seed-certification-evidence';
import { seedProductionProcessesAndCreditBatches } from './seed-credit-batches';

export async function seedDemoProduction(tx: DbTransaction) {
  console.log('Creating production runs...');
  await tx.insert(schema.productionRuns).values(withBootstrapOrg<typeof schema.productionRuns.$inferInsert>([
    {
      id: ids.productionRun1,
      code: 'PR-26-001',
      facilityId: ids.facilityMoshi,
      status: 'complete',
      startTime: demoTimestamps.run1Start,
      endTime: demoTimestamps.run1End,
      reactorId: ids.reactorMoshi1,
      operatorId: ids.operatorNeema,
      feedingRateKgHr: 480,
      residenceTimeMinutes: 45,
      dieselOperationLiters: 14,
      dieselGensetLiters: 4,
      preprocessingFuelLiters: 3,
      electricityKwh: 165,
      electricitySourceCategory: 'ec1_grid_average',
      lowCarbonPercentage: 44,
      biocharOutputKg: 980,
      biocharMoisturePercent: 2,
      biocharDryMassKg: 960.4,
      biocharStorageLocationId: ids.storageCharMoshi,
      feedstockStorageLocationId: ids.storageFeedMoshi,
      feedstockWetMassKg: demoProductionRunFeedstockWetMassKg.run1,
      feedstockMoisturePercent: 16,
      feedstockMassDryKg: 2940,
    },
    {
      id: ids.productionRun2,
      code: 'PR-26-002',
      facilityId: ids.facilityMoshi,
      status: 'complete',
      startTime: demoTimestamps.run2Start,
      endTime: demoTimestamps.run2End,
      reactorId: ids.reactorMoshi1,
      operatorId: ids.operatorJuma,
      feedingRateKgHr: 450,
      residenceTimeMinutes: 42,
      dieselOperationLiters: 12,
      dieselGensetLiters: 3,
      preprocessingFuelLiters: 2,
      electricityKwh: 145,
      electricitySourceCategory: 'ec1_grid_average',
      lowCarbonPercentage: 44,
      biocharOutputKg: 720,
      biocharMoisturePercent: 2,
      biocharDryMassKg: 705.6,
      biocharStorageLocationId: ids.storageCharMoshi,
      feedstockStorageLocationId: ids.storageFeedCoffee,
      feedstockWetMassKg: demoProductionRunFeedstockWetMassKg.run2,
      feedstockMoisturePercent: 12,
      feedstockMassDryKg: 2200,
    },
    {
      id: ids.productionRun3,
      code: 'PR-26-003',
      facilityId: ids.facilityMoshi,
      status: 'complete',
      startTime: demoTimestamps.run3Start,
      endTime: demoTimestamps.run3End,
      reactorId: ids.reactorMoshi2,
      operatorId: ids.operatorNeema,
      feedingRateKgHr: 380,
      residenceTimeMinutes: 55,
      dieselOperationLiters: 10,
      dieselGensetLiters: 4,
      preprocessingFuelLiters: 2,
      electricityKwh: 120,
      electricitySourceCategory: 'ec1_grid_average',
      lowCarbonPercentage: 44,
      biocharOutputKg: 850,
      biocharMoisturePercent: 2,
      biocharDryMassKg: 833,
      biocharStorageLocationId: ids.storageCharMoshi,
      feedstockStorageLocationId: ids.storageFeedMoshi,
      feedstockWetMassKg: demoProductionRunFeedstockWetMassKg.run3,
      feedstockMoisturePercent: 18,
      feedstockMassDryKg: 2460,
    },
  ]));

  console.log('Creating production run feedstock draws...');
  await tx.insert(schema.productionRunFeedstockDraws).values(withBootstrapOrg<typeof schema.productionRunFeedstockDraws.$inferInsert>([
    {
      productionRunId: ids.productionRun1,
      storageLocationId: ids.storageFeedMoshi,
      wetMassKg: demoProductionRunFeedstockWetMassKg.run1,
    },
    {
      productionRunId: ids.productionRun2,
      storageLocationId: ids.storageFeedCoffee,
      wetMassKg: demoProductionRunFeedstockWetMassKg.run2,
    },
    {
      productionRunId: ids.productionRun3,
      storageLocationId: ids.storageFeedMoshi,
      wetMassKg: demoProductionRunFeedstockWetMassKg.run3,
    },
  ]));

  console.log('Creating production run feedstock links...');
  await tx.insert(schema.productionRunFeedstocks).values(withBootstrapOrg<typeof schema.productionRunFeedstocks.$inferInsert>([
    {
      id: ids.prodFeedLink1,
      productionRunId: ids.productionRun1,
      feedstockId: ids.feedstock1,
      wetMassUsedKg: demoProductionRunFeedstockWetMassKg.run1,
    },
    {
      id: ids.prodFeedLink2,
      productionRunId: ids.productionRun2,
      feedstockId: ids.feedstock2,
      wetMassUsedKg: demoProductionRunFeedstockWetMassKg.run2,
    },
    {
      id: ids.prodFeedLink3,
      productionRunId: ids.productionRun3,
      feedstockId: ids.feedstock3,
      wetMassUsedKg: demoProductionRunFeedstockWetMassKg.run3,
    },
  ]));

  const productionRunReadingRows = buildProductionRunReadings([
    {
      idBase: 2500,
      productionRunId: ids.productionRun1,
      start: demoTimestamps.run1Start,
      end: demoTimestamps.run1End,
      temperatureStartC: 418,
      temperaturePeakC: 566,
      pressureStartBar: 0.07,
      pressurePeakBar: 0.12,
      gasStartRate: 0.18,
      gasPeakRate: 0.31,
    },
    {
      idBase: 2650,
      productionRunId: ids.productionRun2,
      start: demoTimestamps.run2Start,
      end: demoTimestamps.run2End,
      temperatureStartC: 406,
      temperaturePeakC: 548,
      pressureStartBar: 0.065,
      pressurePeakBar: 0.105,
      gasStartRate: 0.16,
      gasPeakRate: 0.28,
    },
    {
      idBase: 2800,
      productionRunId: ids.productionRun3,
      start: demoTimestamps.run3Start,
      end: demoTimestamps.run3End,
      temperatureStartC: 392,
      temperaturePeakC: 526,
      pressureStartBar: 0.06,
      pressurePeakBar: 0.098,
      gasStartRate: 0.145,
      gasPeakRate: 0.255,
    },
  ], DEC_ORG_ID);

  console.log(`Creating ${productionRunReadingRows.length} production run readings...`);
  await tx.insert(schema.productionRunReadings).values(productionRunReadingRows);

  // Production processes + their credit batches must exist before samples
  // (the samples.credit_batch_id FK, added in migration 0057). The shared
  // `seedProductionProcessesAndCreditBatches` builds them; it is invoked here
  // — before samples — rather than after applications.
  await seedProductionProcessesAndCreditBatches(
    tx,
    DEC_ORG_ID,
    ids,
    demoTimestamps,
  );

  // Each sampled credit batch pools >=3 replicates with a complete
  // H/C_org + O/C_org pair (durability gate, module §8.3.1 / §3 Table 2).
  // Moshi is a 1000-year facility (ADR 0021), so EVERY batch's samples carry
  // the R0 + TGA evidence the intake guard requires (requireBatchTierEvidence,
  // issue #341) plus the per-sample s_fraction (proportion of R0 readings
  // >= 2% — the inertinite fraction) the 1000-year sequestration blueprint
  // consumes. Molar ratios are consistent with the elemental percentages
  // (H/C_org = (H/1)/(C_org/12), O/C_org = (O/16)/(C_org/12)).
  console.log('Creating samples...');
  await tx.insert(schema.samples).values(withBootstrapOrg<typeof schema.samples.$inferInsert>([
    // --- Credit batch 1 (1000-year, woodchips): runs 1 + 3, 3 replicates ---
    {
      id: ids.sample1,
      productionRunId: ids.productionRun1,
      creditBatchId: ids.creditBatch1,
      samplingTime: new Date('2026-05-13T09:30:00.000Z'),
      sampleCode: 'SAM-26-001',
      weightGrams: 520,
      volumeMl: 980,
      labName: 'Kibo Analytical Labs',
      labAccreditation: 'ISO 17025',
      analysisDate: '2026-05-20',
      totalCarbonPercent: 79.2,
      inorganicCarbonPercent: 0.9,
      organicCarbonPercent: 78.3,
      totalHydrogenPercent: 1.8,
      totalOxygenPercent: 7.5,
      hToCOrgRatio: 0.27,
      oToCOrgRatio: 0.07,
      ashContentPercent: 9.5,
      moistureContentPercent: 4.8,
      randomReflectanceR0Percent: 2.85,
      r0MeasurementCount: 100,
      reactiveCarbonPercent: 32.6,
      residualCarbonPercent: 67.4,
      sReflectanceFraction: 0.92,
      r0AnalysisDate: '2026-05-20',
      tgaAnalysisDate: '2026-05-20',
    },
    {
      id: ids.sample3,
      productionRunId: ids.productionRun3,
      creditBatchId: ids.creditBatch1,
      samplingTime: new Date('2026-05-17T10:00:00.000Z'),
      sampleCode: 'SAM-26-003',
      weightGrams: 510,
      volumeMl: 960,
      labName: 'Kibo Analytical Labs',
      labAccreditation: 'ISO 17025',
      analysisDate: '2026-05-24',
      totalCarbonPercent: 77.8,
      inorganicCarbonPercent: 1.0,
      organicCarbonPercent: 76.8,
      totalHydrogenPercent: 2.0,
      totalOxygenPercent: 8.7,
      hToCOrgRatio: 0.31,
      oToCOrgRatio: 0.09,
      ashContentPercent: 10.8,
      moistureContentPercent: 5.4,
      randomReflectanceR0Percent: 2.75,
      r0MeasurementCount: 100,
      reactiveCarbonPercent: 32.1,
      residualCarbonPercent: 67.9,
      sReflectanceFraction: 0.90,
      r0AnalysisDate: '2026-05-24',
      tgaAnalysisDate: '2026-05-24',
    },
    {
      // Third replicate drawn from the curing pad the morning after run 3.
      // Together these three Samples represent the credit batch (§8.3.1).
      id: ids.sample4,
      productionRunId: ids.productionRun3,
      creditBatchId: ids.creditBatch1,
      samplingTime: new Date('2026-05-18T08:30:00.000Z'),
      sampleCode: 'SAM-26-004',
      weightGrams: 505,
      volumeMl: 950,
      labName: 'Kibo Analytical Labs',
      labAccreditation: 'ISO 17025',
      analysisDate: '2026-05-24',
      totalCarbonPercent: 80.4,
      inorganicCarbonPercent: 0.8,
      organicCarbonPercent: 79.6,
      totalHydrogenPercent: 1.7,
      totalOxygenPercent: 6.9,
      hToCOrgRatio: 0.25,
      oToCOrgRatio: 0.07,
      ashContentPercent: 8.9,
      moistureContentPercent: 4.6,
      randomReflectanceR0Percent: 2.9,
      r0MeasurementCount: 100,
      reactiveCarbonPercent: 32.4,
      residualCarbonPercent: 67.6,
      sReflectanceFraction: 0.93,
      r0AnalysisDate: '2026-05-24',
      tgaAnalysisDate: '2026-05-24',
    },
    // --- Credit batch 2 (1000-year, coffee husk): run 2, 3 replicates
    // with R0 petrography + TGA evidence. Sample means reconcile with the
    // batch's stored meanRandomReflectancePercent (2.8) and
    // meanNonReactiveCarbonPercent (68). ---
    {
      id: ids.sample2,
      productionRunId: ids.productionRun2,
      creditBatchId: ids.creditBatch2,
      samplingTime: new Date('2026-05-15T09:00:00.000Z'),
      sampleCode: 'SAM-26-002',
      weightGrams: 485,
      volumeMl: 920,
      labName: 'Kibo Analytical Labs',
      labAccreditation: 'ISO 17025',
      analysisDate: '2026-05-22',
      totalCarbonPercent: 81.5,
      inorganicCarbonPercent: 0.7,
      organicCarbonPercent: 80.8,
      totalHydrogenPercent: 1.5,
      totalOxygenPercent: 6.0,
      hToCOrgRatio: 0.22,
      oToCOrgRatio: 0.06,
      ashContentPercent: 8.2,
      moistureContentPercent: 5.1,
      randomReflectanceR0Percent: 2.9,
      r0MeasurementCount: 100,
      reactiveCarbonPercent: 31.8,
      residualCarbonPercent: 68.2,
      sReflectanceFraction: 0.94,
      r0AnalysisDate: '2026-05-22',
      tgaAnalysisDate: '2026-05-22',
    },
    {
      id: ids.sample5,
      productionRunId: ids.productionRun2,
      creditBatchId: ids.creditBatch2,
      samplingTime: new Date('2026-05-16T09:15:00.000Z'),
      sampleCode: 'SAM-26-005',
      weightGrams: 495,
      volumeMl: 940,
      labName: 'Kibo Analytical Labs',
      labAccreditation: 'ISO 17025',
      analysisDate: '2026-05-23',
      totalCarbonPercent: 82.1,
      inorganicCarbonPercent: 0.6,
      organicCarbonPercent: 81.5,
      totalHydrogenPercent: 1.4,
      totalOxygenPercent: 5.4,
      hToCOrgRatio: 0.21,
      oToCOrgRatio: 0.05,
      ashContentPercent: 7.8,
      moistureContentPercent: 4.9,
      randomReflectanceR0Percent: 2.8,
      r0MeasurementCount: 100,
      reactiveCarbonPercent: 32.4,
      residualCarbonPercent: 67.6,
      sReflectanceFraction: 0.91,
      r0AnalysisDate: '2026-05-23',
      tgaAnalysisDate: '2026-05-23',
    },
    {
      id: ids.sample6,
      productionRunId: ids.productionRun2,
      creditBatchId: ids.creditBatch2,
      samplingTime: new Date('2026-05-17T08:45:00.000Z'),
      sampleCode: 'SAM-26-006',
      weightGrams: 500,
      volumeMl: 955,
      labName: 'Kibo Analytical Labs',
      labAccreditation: 'ISO 17025',
      analysisDate: '2026-05-24',
      totalCarbonPercent: 80.9,
      inorganicCarbonPercent: 0.8,
      organicCarbonPercent: 80.1,
      totalHydrogenPercent: 1.6,
      totalOxygenPercent: 6.4,
      hToCOrgRatio: 0.24,
      oToCOrgRatio: 0.06,
      ashContentPercent: 8.5,
      moistureContentPercent: 5.2,
      randomReflectanceR0Percent: 2.7,
      r0MeasurementCount: 100,
      reactiveCarbonPercent: 31.9,
      residualCarbonPercent: 68.1,
      sReflectanceFraction: 0.89,
      r0AnalysisDate: '2026-05-24',
      tgaAnalysisDate: '2026-05-24',
    },
  ]));

  // ============================================================
  // PRODUCTS: Formulations, Biochar Products
  // ============================================================

}
