/**
 * Auto-generate entity codes when not provided
 * Format: {PREFIX}-{YY}-{NNN} (e.g., BP-26-001)
 */

import { db } from "@/db";
import { sql } from "drizzle-orm";
import type { PgTable, PgColumn } from "drizzle-orm/pg-core";

const MAX_RETRIES = 3;

/** Two-digit current year for code generation (e.g. 2026 -> "26"). */
function currentYearShort(): string {
  return String(new Date().getFullYear() % 100).padStart(2, "0");
}

/**
 * Generate the next sequential code for an entity.
 *
 * Queries the DB for the highest existing code matching the prefix + current year,
 * then returns the next sequential code.
 *
 * @param prefix - Entity prefix (e.g., "BP", "FAC")
 * @param table - Drizzle table reference
 * @param codeColumn - The code column on the table
 * @returns Next sequential code like "BP-26-001"
 */
export async function generateNextCode(
  prefix: string,
  table: PgTable,
  codeColumn: PgColumn
): Promise<string> {
  const year = currentYearShort();
  const pattern = `${prefix}-${year}-%`;

  // Find the highest existing code number for this prefix + year
  const result = await db
    .select({
      maxCode: sql<string>`max(${codeColumn})`.as("max_code"),
    })
    .from(table)
    .where(sql`${codeColumn} like ${pattern}`);

  const maxCode = result[0]?.maxCode;
  let nextNumber = 1;

  if (maxCode) {
    // Extract the numeric suffix: "BP-2026-042" -> 42
    const parts = maxCode.split("-");
    const lastPart = parts[parts.length - 1];
    const parsed = parseInt(lastPart, 10);
    if (!isNaN(parsed)) {
      nextNumber = parsed + 1;
    }
  }

  const paddedNumber = String(nextNumber).padStart(3, "0");
  return `${prefix}-${year}-${paddedNumber}`;
}

/**
 * Generate multiple sequential codes in one call.
 * Avoids the duplicate code bug when generating codes before a batch insert.
 */
export async function generateNextCodes(
  prefix: string,
  table: PgTable,
  codeColumn: PgColumn,
  count: number
): Promise<string[]> {
  const year = currentYearShort();
  const pattern = `${prefix}-${year}-%`;

  const result = await db
    .select({
      maxCode: sql<string>`max(${codeColumn})`.as("max_code"),
    })
    .from(table)
    .where(sql`${codeColumn} like ${pattern}`);

  const maxCode = result[0]?.maxCode;
  let nextNumber = 1;

  if (maxCode) {
    const parts = maxCode.split("-");
    const lastPart = parts[parts.length - 1];
    const parsed = parseInt(lastPart, 10);
    if (!isNaN(parsed)) {
      nextNumber = parsed + 1;
    }
  }

  return Array.from({ length: count }, (_, i) => {
    const paddedNumber = String(nextNumber + i).padStart(3, "0");
    return `${prefix}-${year}-${paddedNumber}`;
  });
}

/**
 * Check if an error is a Postgres unique constraint violation on the code column.
 * Matches the specific constraint name pattern generated by Drizzle's .unique().
 */
function isCodeUniqueViolation(error: unknown, codeColumn: PgColumn): boolean {
  if (!(error instanceof Error)) return false;
  const msg = error.message;
  // Postgres unique violation includes "duplicate key value violates unique constraint"
  // and the constraint name (e.g., "facilities_code_unique")
  const columnName = codeColumn.name;
  return (
    msg.includes("duplicate key") &&
    msg.includes(`_${columnName}_unique`)
  );
}

/**
 * Execute an insert operation with auto-generated code, retrying on
 * duplicate code collisions. This handles the race condition where
 * concurrent requests generate the same sequential code.
 *
 * @param prefix - Entity prefix (e.g., "OR", "FAC")
 * @param table - Drizzle table reference
 * @param codeColumn - The code column on the table
 * @param userCode - User-provided code (empty/undefined = auto-generate)
 * @param insertFn - Callback that performs the insert with the given code
 * @returns The result from insertFn
 */
export async function withAutoCode<T>(
  prefix: string,
  table: PgTable,
  codeColumn: PgColumn,
  userCode: string | undefined | null,
  insertFn: (code: string) => Promise<T>
): Promise<T> {
  // If user provided a code, use it directly with a friendly error on duplicates
  if (userCode) {
    try {
      return await insertFn(userCode);
    } catch (error) {
      if (isCodeUniqueViolation(error, codeColumn)) {
        throw new Error(`Code "${userCode}" already exists. Please use a different code.`);
      }
      throw error;
    }
  }

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const code = await generateNextCode(prefix, table, codeColumn);
    try {
      return await insertFn(code);
    } catch (error) {
      if (isCodeUniqueViolation(error, codeColumn) && attempt < MAX_RETRIES - 1) {
        // Brief pause before retry to let the other transaction commit
        await new Promise((resolve) => setTimeout(resolve, 50 * (attempt + 1)));
        continue;
      }
      throw error;
    }
  }

  // Should never reach here, but TypeScript needs it
  throw new Error(`Failed to generate unique code after ${MAX_RETRIES} attempts`);
}
